# Generated by Django 2.2.7 on 2020-08-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200813_1719'),
    ]

    operations = [
    ]
