# Generated by Django 2.2.7 on 2020-08-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_entity_sysname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='region',
            field=models.SmallIntegerField(choices=[(0, '市级直属'), (1, '青羊区'), (2, '锦江区'), (3, '金牛区'), (4, '武侯区'), (5, '高新区'), (6, '天府新区'), (7, '成华区'), (8, '新都区'), (9, '温江区'), (10, '龙泉驿区'), (11, '青白江区'), (12, '金堂县'), (13, '双流区'), (14, '双流区'), (15, '新津区'), (16, '彭州市')], default=0, verbose_name='所属地区'),
        ),
    ]
