"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')__4+br89g(k+mzg+@(n3g20a1d4=v7wktly3esrtv0#u)8%*h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'assets',
    'gzjj'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/



LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
#STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static", ),
]

#STATIC_ROOT = os.path.join(BASE_DIR, "/pytest/django/cdszwy/static/")


# 媒体文件的路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/media/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}




### simpleui 配置 ###
# 隐藏simpleui服务器信息
SIMPLEUI_HOME_INFO = False
# Logo图标
SIMPLEUI_LOGO = '/static/custom/img/logo.png'
# False的时候，默认从第三方的cdn获取加载静态资源 2.1.3或以上的版本
SIMPLEUI_STATIC_OFFLINE = True


LOGIN_URL = 'admin/login/'
LOGIN_REDIRECT_URL = '/'
# 认证登录




SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menus': [

        {
            'app': 'assets',
            'name': '资产管理',
            'icon': 'fas fa-archive',
            'models': [
                {
                    'name': '资产信息',
                    'url': 'assets/asset',
                    'icon': 'fas fa-archive'
                },
                {
                    'name': '系统列表',
                    'url': 'assets/sysname',
                    'icon': 'fas fa-landmark'
                },
      
                {
                    'name': '单位列表',
                    'url': 'assets/entity',
                    'icon': 'fas fa-address-book'
                },


            ]
        },

        {
            'app': 'gzjj',
            'name': '工作交接',
            'icon': 'fas fa-address-book',
            'models': [
                {
                    'name': '交接列表',
                    'url': 'gzjj/gzjj',
                    'icon': 'fas fa-list'
                },

            ]
        },


        {
            'app': 'auth',
            'name': '权限认证',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户',
                    'icon': 'fa fa-user',
                    'url': 'auth/user'
                },
                {
                    'name': '用户组',
                    'icon': 'fa fa-user-friends',
                    'url': 'auth/group'
                }

            ]
        },




        {
            'name': 'github',
            'url': 'https://github.com/cwbird/cmdb',
            'icon': 'fab fa-github'
        }]
}
