# Generated by Django 2.2.7 on 2020-08-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gzjj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gzjj',
            name='stat',
            field=models.SmallIntegerField(choices=[(0, '未完成'), (1, '进行中'), (2, '已完成')], default=0, verbose_name='完成状态'),
        ),
    ]
