# Generated by Django 2.2.7 on 2020-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gzjj', '0003_gzjj_beizhu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gzjj',
            name='beizhu',
        ),
        migrations.AddField(
            model_name='gzjj',
            name='cl_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='处理人员'),
        ),
    ]
