# Generated by Django 2.2.7 on 2020-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gzjj', '0004_auto_20200820_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gzjj',
            name='name',
            field=models.CharField(max_length=32, verbose_name='交接人员'),
        ),
    ]
